sudo: required
language: php
<<<<<<< HEAD
=======
services:
  - mysql
>>>>>>> b95d6565525b3f64a4f77dbdc157d7b6b47bbcc7
matrix:
  fast_finish: true
  include:
  - php: 7.0
  - php: 5.3
<<<<<<< HEAD
    env:
      SKIP_STYLE_CHECK=1
  - php: 5.4
    env:
      SKIP_STYLE_CHECK=1
  - php: 5.5
    env:
      SKIP_STYLE_CHECK=1
  - php: 5.6
    env:
      SKIP_STYLE_CHECK=1
      EXECUTE_BUILD_DOCS=true
  - php: hhvm
    env:
      SKIP_STYLE_CHECK=1
=======
    env: SKIP_STYLE_CHECK=1
  - php: 5.4
    env: SKIP_STYLE_CHECK=1
  - php: 5.5
    env: SKIP_STYLE_CHECK=1
  - php: 5.6
    env: SKIP_STYLE_CHECK=1 EXECUTE_BUILD_DOCS=true EXECUTE_BUILD_SCHEMA=false
#  - php: hhvm
#    env: SKIP_STYLE_CHECK=1
>>>>>>> b95d6565525b3f64a4f77dbdc157d7b6b47bbcc7

  allow_failures:
  - php: hhvm

cache:
<<<<<<< HEAD
  - pip
  - directories:
    - vendor
=======
  directories:
    - vendor
    - $HOME/.cache/pip
>>>>>>> b95d6565525b3f64a4f77dbdc157d7b6b47bbcc7
    - $HOME/.composer/cache

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y snmp
<<<<<<< HEAD

install:
  - composer install --prefer-dist --no-interaction
  - pip install --user snmpsim
=======
  - mysql -e 'CREATE DATABASE librenms_phpunit_78hunjuybybh;'

install:
  - composer install --prefer-dist --no-interaction
  - pip install --user pyasn1==0.2.2
  - pip install --user snmpsim==0.3.1
>>>>>>> b95d6565525b3f64a4f77dbdc157d7b6b47bbcc7
  - pip install --user pylint

before_script:
  - python2 $HOME/.local/bin/snmpsimd.py --data-dir=$TRAVIS_BUILD_DIR/tests/snmpsim --agent-udpv4-endpoint=127.0.0.1:11161 --logging-method=file:/tmp/snmpsimd.log --daemon --pid-file=/tmp/snmpsimd.pid

after_success:
<<<<<<< HEAD
=======
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test $EXECUTE_BUILD_SCHEMA == "true" && bash scripts/deploy-schema.sh
>>>>>>> b95d6565525b3f64a4f77dbdc157d7b6b47bbcc7
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test $EXECUTE_BUILD_DOCS == "true" && bash scripts/deploy-docs.sh

after_failure:
  - cat /tmp/snmpsimd.log

script:
  - php scripts/pre-commit.php -l
  - php scripts/pre-commit.php -s
<<<<<<< HEAD
  - SNMPSIM=1 phpunit --stop-on-failure
=======
  - SNMPSIM=1 DBTEST=1 vendor/bin/phpunit --stop-on-failure
>>>>>>> b95d6565525b3f64a4f77dbdc157d7b6b47bbcc7
  - bash -n daily.sh
  - pylint -E poller-wrapper.py discovery-wrapper.py poller-service.py
